environment: debug

server:
  host: 0.0.0.0
  port: 8080

data:
  database:
    master:
      driver: mongodb
      source: "mongodb://username:password@localhost:27017/userdb"
      max_idle_conns: 10
      max_open_conns: 100

logger:
  level: debug
  format: json
  output: stdout
  enable_caller: true
